# Generated by Django 5.2.1 on 2025-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=1028),
        ),
    ]
