# Generated by Django 5.2.1 on 2025-11-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1028)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "default_related_name": "questions",
            },
        ),
    ]
